export const commonText = {
  welcome: "Welcome",
  letstart: "Let’s Get You Started With Lintlock",
  email: "Email Address",
  enteremailaddress: "Enter your email address",
  password: "Password",
  enterpassword: "Enter your password",
  forgotPassword: "Forgot password?",
  login: "Login",
  resetPassword: "Reset Password",
  CheckInbox: "Check your inbox, please!",
  didnotLink: "Didn’t get the link?",
  resendit: "Resend it",
  gotoEmail: "Go To Email",
  goodmorning: "Good Morning",
  dashboard: "Dashboard",
  Newrepair: "New Repair",
  Update: "Update",
  UpdateProfle: "Update Profile",
  start: "Start",
  status: "Status",
  reason: "Reason",
  photos: "Photos",
  report: "Report",
  logout: "Logout",
  Repairinprogress: "Repairs In progress",
  CompletedRepairs: "Completed Repairs",
  Reportedissues: "Reported Issues",
  Reportanissue: "Report An Issue",
  addnotes: "Add Notes (Optional)",
  uploadanimage: "Upload An Image",
  enterReason: "Enter Reason Here",
  reportissue: "Report An Issue",
  title: "Title",
  entertitle: "Enter Issue Title Here",
  location: "Location",
  enterlocation: "Enter Location",
  notification: "Notifications",
  issueDescription: "Enter Issue Description Here",
  submit: "Submit",
  markasRead: "Mark as Read",
  profile: "Profile",
  phone: "Phone Number",
  manageProfile: "Manage Profile",
  fullName: "Full Name",
  editprofile: "Edit Profile",
  inboxmessage:
    "We have sent a verification link to your email address. Please check your inbox (and spam or junk folder if you don’t see it) and click on the link to confirm your email address.",
  dummyText:
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
};
export const validationConstants = {
  noInternet: "Please check your internet connection",
  emailRequired: "Please enter email address.",
  invalidEmail: "Please enter valid email address.",
  passwordRequired: "Please enter password.",
  invalidPasswordLogin: "Please enter password.",
  otpRequired: "Please enter OTP.",
  invalidOtp: "Please enter valid OTP.",
  enternewPassword: "Please enter new password.",
  invalidPassword:
    "New password must be at least 8 characters long with uppercase, lowercase, number, special character, and no spaces.",
  enterconfirmPassword: "Please enter confirm password.",
  passwordNotMatch: "New password and confirm password does not match.",
};

export const validationSchema = {
  email: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
  password:
    /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/,
};
