import { DevicePermissions } from "../screens/devicePermissions/devicePermissions";

export const commonText = {
  welcomeMessage: "Welcome Back, Buddy !",
  letstart: "Let's Get You Back In",
  email: "Email Address",
  enteremailaddress: "Enter your email address",
  password: "Password",
  enterpassword: "Enter your password",
  enterConfirmPassword: "Confirm your password",
  forgotPassword: "Forgot password?",
  newToVirtue: "New To Virtue ?",
  createAccount: "Create Account",
  letsGetStarted: "Let’s get started, buddy !",
  yourJOurneyBegingHere: "Your journey begins here",
  name: "Name",
  enterName: "Enter Name",
  confirmPassword: "Confirm Password",
  letsGo: "Let's Go",
  alreadyHaveAnAccount: "Already have an acount",
  login: "Login",
  almostThere: "Almost there, buddy!",
  codeSentDescription:
    "We’ve sent a 4-digit code to your email. Enter it below to verify your account",
  veiryAndContinue: "Verify & Continue",
  resendOtpIn: "Resend OTP in",
  letsFixThis: "Let’s fix this, buddy",
  dontStress: "Don’t stress. We’ll get you back in within seconds",
  continue: "Continue",
  youAreAlmostBack: "You’re almost back, buddy",
  justSetYOurPassword: "Just set your new password below.",
  resetPassword: "Reset Password",
  Update: "Update",
  UpdateProfle: "Update Profile",
  logout: "Logout",
  uploadanimage: "Upload An Image",
  dummyText:
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
  profileName: "Premium User",
  profileHandle: "unique_creator",
  profileBio:
    "Creating digital experiences and loving life. 🚀 \nAlways building, always growing. Let's connect!",
  profileLink: "🔗 myuniverse.com/unique",
  posts: "Posts",
  followers: "Followers",
  following: "Following",
  highlights: "Highlights",
  achievementVault: "Achievement Vault",
  reels: "Reels",
  tags: "Tags",
  editProfile: "Edit Profile",
  shareProfile: "Share Profile",
  search: "Search",
  settings: "Settings",
  yourActivity: "Your Activity",
  saved: "Saved",
  archive: "Archive",
  accountPrivacy: "Account Privacy",
  notification: "Notification",
  help: "Help",
  blocked: "Blocked",
  bites: "Bites",
  DevicePermissions: "Device Permissions",
  ChangePassword: "Change Password",
  dataUsage: "Data Usage",
  monetization: "Monetization",
  tagsAndMentions: "Tags and Mentions",
  ratings: "Ratings",
};
export const validationConstants = {
  noInternet: "Please check your internet connection.",
  emailRequired: "Please enter email address.",
  invalidEmail: "Please enter valid email address.",
  passwordRequired: "Please enter password.",
  invalidPasswordLogin: "Please enter valid password.",
  otpRequired: "Please enter OTP.",
  invalidOtp: "Please enter valid OTP.",
  enternewPassword: "Please enter new password.",
  invalidPassword:
    "New password must be at least 8 characters long with uppercase, lowercase, number, special character, and no spaces.",
  enterconfirmPassword: "Please enter confirm password.",
  passwordNotMatch: "New password and confirm password does not match.",
};

export const validationSchema = {
  email: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
  password:
    /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/,
};
