import { StyleSheet } from "react-native";
import { colors, scales, topInset } from "../../utils";
import { fontFamily } from "../../assets";

export const styles = StyleSheet.create({
  scrollContent: {
    paddingBottom: scales(40),
  },
  heroContainer: {
    width: "100%",
    height: scales(280) + topInset,
    position: "relative",
    overflow: "hidden",
  },
  ratingStar: {
    height: scales(20),
    width: scales(20),
    resizeMode: "contain",
    tintColor: colors.yellow,
    marginRight: scales(10),
  },
  heroImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  floatingBackBtn: {
    position: "absolute",
    top: topInset > 0 ? topInset + scales(8) : scales(36),
    left: scales(16),
    zIndex: 20,
  },
  backIcon: {
    width: scales(16),
    height: scales(16),
    resizeMode: "contain",
  },
  heroPlayBtn: {
    position: "absolute",
    top: "50%",
    left: "50%",
    marginLeft: -scales(32),
    marginTop: -scales(32),
    width: scales(64),
    height: scales(64),
    borderRadius: scales(32),
    overflow: "hidden",
    shadowColor: colors.storyRing,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.6,
    shadowRadius: 14,
    elevation: 10,
    zIndex: 15,
  },
  playGradientCircle: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  playIcon: {
    width: scales(24),
    height: scales(24),
    resizeMode: "contain",
    marginLeft: scales(3),
  },
  detailsContainer: {
    paddingHorizontal: scales(16),
    marginTop: scales(14),
  },
  movieTitle: {
    color: colors.white,
    fontFamily: fontFamily.bold,
    fontSize: scales(24),
    letterSpacing: 0.2,
  },
  movieTagline: {
    color: colors.transparentWhite85,
    fontFamily: fontFamily.regular,
    fontSize: scales(13),
    marginTop: scales(4),
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: scales(8),
    marginTop: scales(12),
    marginBottom: scales(4),
  },
  metaBadge: {
    backgroundColor: colors.transparentWhite10,
    paddingHorizontal: scales(10),
    paddingVertical: scales(4),
    borderRadius: scales(10),
    borderWidth: 1,
    borderColor: colors.transparentWhite12,
  },
  metaBadgeText: {
    color: colors.transparentWhite85,
    fontFamily: fontFamily.medium,
    fontSize: scales(11),
  },
  metaBadgeAccent: {
    backgroundColor: "rgba(245, 60, 109, 0.15)",
    paddingHorizontal: scales(10),
    paddingVertical: scales(4),
    borderRadius: scales(10),
    borderWidth: 1,
    borderColor: colors.magenta,
  },
  metaBadgeAccentText: {
    color: colors.white,
    fontFamily: fontFamily.bold,
    fontSize: scales(11),
  },
  sectionHeader: {
    color: colors.white,
    fontFamily: fontFamily.bold,
    fontSize: scales(18),
  },
  descriptionText: {
    color: colors.transparentWhite85,
    fontFamily: fontFamily.regular,
    fontSize: scales(14),
    lineHeight: scales(20),
    marginTop: scales(6),
  },
  ratingsCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.transparentWhite5,
    borderWidth: 1,
    borderColor: colors.transparentWhite10,
    borderRadius: scales(14),
    paddingHorizontal: scales(14),
    paddingVertical: scales(12),
  },
  ratingScoreBox: {
    flexDirection: "row",
    alignItems: "center",
  },
  ratingScoreText: {
    color: colors.white,
    fontFamily: fontFamily.bold,
    fontSize: scales(18),
  },
  ratingMaxText: {
    color: colors.transparentWhite40,
    fontFamily: fontFamily.regular,
    fontSize: scales(12),
    marginLeft: scales(2),
  },
  ratingCountText: {
    color: colors.transparentWhite40,
    fontFamily: fontFamily.regular,
    fontSize: scales(12),
    marginLeft: scales(8),
  },
  seeAllRatingsBtn: {
    backgroundColor: colors.transparentWhite10,
    paddingHorizontal: scales(12),
    paddingVertical: scales(6),
    borderRadius: scales(10),
  },
  seeAllRatingsText: {
    color: colors.storyRing,
    fontFamily: fontFamily.semiBold,
    fontSize: scales(12),
  },
  castScroll: {
    gap: scales(12),
  },
  actorCard: {
    width: scales(95),
    alignItems: "center",
    backgroundColor: colors.transparentWhite5,
    borderWidth: 1,
    borderColor: colors.transparentWhite10,
    borderRadius: scales(12),
    padding: scales(10),
  },
  actorAvatar: {
    width: scales(44),
    height: scales(44),
    borderRadius: scales(22),
    marginBottom: scales(8),
  },
  actorName: {
    color: colors.storyRing,
    fontFamily: fontFamily.bold,
    fontSize: scales(12),
    textAlign: "center",
  },
  actorRole: {
    color: colors.transparentWhite40,
    fontFamily: fontFamily.regular,
    fontSize: scales(10),
    textAlign: "center",
    marginTop: scales(2),
  },
  mainTrailerCard: {
    width: "100%",
    height: scales(170),
    borderRadius: scales(16),
    overflow: "hidden",
    position: "relative",
    backgroundColor: colors.transparentWhite5,
  },
  trailerImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  trailerDimOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
  },
  trailerPlayCircle: {
    position: "absolute",
    top: scales(52),
    alignSelf: "center",
    width: scales(44),
    height: scales(44),
    borderRadius: scales(22),
    backgroundColor: colors.blue,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
    overflow: "hidden",
  },
  miniPlayIcon: {
    width: scales(15),
    height: scales(15),
    resizeMode: "contain",
    marginLeft: scales(2),
  },
  trailerContent: {
    position: "absolute",
    bottom: scales(12),
    left: scales(12),
    right: scales(12),
    flexDirection: "row",
    alignItems: "center",
    gap: scales(8),
  },
  durationTag: {
    backgroundColor: colors.transparentBlack30,
    paddingHorizontal: scales(8),
    paddingVertical: scales(3),
    borderRadius: scales(6),
  },
  durationTagText: {
    color: colors.white,
    fontFamily: fontFamily.bold,
    fontSize: scales(10),
  },
  trailerTitle: {
    color: colors.white,
    fontFamily: fontFamily.bold,
    fontSize: scales(13),
    flex: 1,
  },
  btsScroll: {
    gap: scales(12),
  },
  btsCard: {
    width: scales(160),
    height: scales(110),
    borderRadius: scales(12),
    overflow: "hidden",
    position: "relative",
    backgroundColor: colors.transparentWhite5,
  },
  btsImage: {
    ...StyleSheet.absoluteFillObject,
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  btsDimOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.45)",
  },
  btsPlayCircle: {
    position: "absolute",
    top: scales(26),
    alignSelf: "center",
    width: scales(32),
    height: scales(32),
    borderRadius: scales(16),
    backgroundColor: colors.blue,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
    overflow: "hidden",
  },
  btsDurationTag: {
    position: "absolute",
    top: scales(6),
    right: scales(6),
    backgroundColor: colors.transparentBlack30,
    paddingHorizontal: scales(6),
    paddingVertical: scales(2),
    borderRadius: scales(4),
  },
  btsTitle: {
    position: "absolute",
    bottom: scales(8),
    left: scales(8),
    right: scales(8),
    color: colors.white,
    fontFamily: fontFamily.semiBold,
    fontSize: scales(10),
    lineHeight: scales(13),
  },
  reviewSheetContent: {
    paddingHorizontal: scales(16),
    paddingBottom: scales(30),
  },
  sheetHeaderScore: {
    alignItems: "center",
    paddingVertical: scales(10),
  },
  sheetBigScore: {
    color: colors.white,
    fontFamily: fontFamily.bold,
    fontSize: scales(36),
  },
  sheetMaxScore: {
    color: colors.transparentWhite40,
    fontFamily: fontFamily.regular,
    fontSize: scales(12),
  },
  sheetTotalRatings: {
    color: colors.blue,
    fontFamily: fontFamily.semiBold,
    fontSize: scales(13),
    marginTop: scales(4),
  },
  reviewItem: {
    backgroundColor: colors.transparentWhite5,
    borderWidth: 1,
    borderColor: colors.transparentWhite10,
    borderRadius: scales(12),
    padding: scales(12),
    marginBottom: scales(10),
  },
  reviewHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: scales(8),
  },
  reviewAvatar: {
    width: scales(32),
    height: scales(32),
    borderRadius: scales(16),
    marginRight: scales(10),
  },
  reviewHeaderMeta: {
    flex: 1,
  },
  reviewAuthor: {
    color: colors.white,
    fontFamily: fontFamily.bold,
    fontSize: scales(13),
  },
  reviewDate: {
    color: colors.transparentWhite40,
    fontFamily: fontFamily.regular,
    fontSize: scales(10),
  },
  reviewBadge: {
    backgroundColor: colors.transparentWhite10,
    paddingHorizontal: scales(8),
    paddingVertical: scales(4),
    borderRadius: scales(8),
  },
  reviewBadgeText: {
    color: colors.white,
    fontFamily: fontFamily.bold,
    fontSize: scales(11),
  },
  reviewComment: {
    color: colors.transparentWhite85,
    fontFamily: fontFamily.regular,
    fontSize: scales(12),
    lineHeight: scales(17),
  },
});
