import { StyleSheet } from "react-native";
import { colors, scales } from "../../utils";
import { fontFamily } from "../../assets";

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  scrollContent: { paddingBottom: scales(60) },
  previewStrip: {
    paddingHorizontal: scales(20),
    paddingVertical: scales(12),
  },
  previewThumb: {
    width: scales(70),
    height: scales(70),
    borderRadius: scales(12),
    marginRight: scales(10),
    overflow: "hidden",
  },
  previewImage: { width: "100%", height: "100%", resizeMode: "cover" },
  previewVideoBadge: {
    position: "absolute",
    top: scales(4),
    left: scales(4),
    backgroundColor: "rgba(0,0,0,0.6)",
    borderRadius: scales(10),
    width: scales(22),
    height: scales(22),
    justifyContent: "center",
    alignItems: "center",
  },
  previewPlayIcon: {
    width: scales(10),
    height: scales(10),
    resizeMode: "contain",
  },
  coverBadge: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.storyRing,
    alignItems: "center",
    paddingVertical: scales(2),
  },
  coverText: {
    color: colors.white,
    fontFamily: fontFamily.bold,
    fontSize: scales(9),
  },
  fields: { paddingHorizontal: scales(20) },
  sectionLabel: {
    color: colors.transparentWhite85,
    fontFamily: fontFamily.bold,
    fontSize: scales(14),
    marginTop: scales(18),
    marginBottom: scales(6),
    letterSpacing: 0.5,
  },
  tagsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: scales(8),
    marginTop: scales(4),
  },
  chip: {
    paddingHorizontal: scales(14),
    paddingVertical: scales(8),
    borderRadius: scales(20),
    borderWidth: 1,
    borderColor: colors.transparentWhite15,
    backgroundColor: colors.transparentWhite5,
  },
  chipSelected: {
    borderColor: colors.storyRing,
    backgroundColor: "rgba(245, 60, 109, 0.2)",
  },
  chipText: {
    color: "rgba(255, 255, 255, 0.6)",
    fontFamily: fontFamily.medium,
    fontSize: scales(12),
  },
  chipTextSelected: { color: colors.white, fontFamily: fontFamily.bold },
  audioRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: scales(14),
    paddingHorizontal: scales(16),
    borderRadius: scales(16),
    borderWidth: 1,
    borderColor: colors.transparentWhite15,
    backgroundColor: colors.transparentWhite5,
    marginTop: scales(4),
  },
  audioLeft: { flexDirection: "row", alignItems: "center", gap: scales(12) },
  audioIcon: {
    width: scales(22),
    height: scales(22),
    tintColor: colors.storyRing,
    resizeMode: "contain",
  },
  audioTitle: {
    color: colors.white,
    fontFamily: fontFamily.semiBold,
    fontSize: scales(14),
  },
  audioSub: {
    color: "rgba(255, 255, 255, 0.5)",
    fontFamily: fontFamily.regular,
    fontSize: scales(12),
    marginTop: scales(2),
  },
  audioArrow: {
    width: scales(16),
    height: scales(16),
    tintColor: "rgba(255, 255, 255, 0.4)",
    resizeMode: "contain",
  },
  visibilityRow: { flexDirection: "row", gap: scales(8), marginTop: scales(4) },
  visOpt: {
    flex: 1,
    paddingVertical: scales(10),
    paddingHorizontal: scales(4),
    borderRadius: scales(12),
    borderWidth: 1,
    borderColor: colors.transparentWhite15,
    backgroundColor: colors.transparentWhite5,
    alignItems: "center",
    justifyContent: "center",
  },
  visOptSelected: {
    borderColor: colors.storyRing,
    backgroundColor: "rgba(245, 60, 109, 0.2)",
  },
  visText: {
    color: "rgba(255, 255, 255, 0.6)",
    fontFamily: fontFamily.medium,
    fontSize: scales(11),
    textAlign: "center",
  },
  visTextSelected: { color: colors.white, fontFamily: fontFamily.bold },
  footer: { paddingHorizontal: scales(20), marginTop: scales(10) },
  postersGrid: { flexDirection: "row", gap: scales(12), marginTop: scales(4) },
  assetCard: {
    flex: 1,
    height: scales(140),
    backgroundColor: colors.transparentWhite5,
    borderRadius: scales(16),
    borderWidth: 1,
    borderColor: colors.transparentWhite15,
    alignItems: "center",
    justifyContent: "center",
    padding: scales(10),
    overflow: "hidden",
    borderStyle: "dashed",
  },
  assetContent: { alignItems: "center", justifyContent: "center" },
  assetIconCircle: {
    width: scales(40),
    height: scales(40),
    borderRadius: scales(20),
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: scales(8),
  },
  assetIcon: {
    width: scales(20),
    height: scales(20),
    tintColor: colors.storyRing,
    resizeMode: "contain",
  },
  assetTitle: {
    fontFamily: fontFamily.bold,
    fontSize: scales(13),
    color: colors.white,
    textAlign: "center",
  },
  assetSubtitle: {
    fontFamily: fontFamily.regular,
    fontSize: scales(10),
    color: "rgba(255, 255, 255, 0.5)",
    textAlign: "center",
    marginTop: scales(2),
  },
  assetRatioBadge: {
    position: "absolute",
    top: scales(8),
    right: scales(8),
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderRadius: scales(8),
    paddingHorizontal: scales(6),
    paddingVertical: scales(2),
  },
  assetRatioText: {
    fontFamily: fontFamily.bold,
    fontSize: scales(9),
    color: colors.white,
  },
  assetImage: {
    ...StyleSheet.absoluteFillObject,
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  assetImageOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.45)",
    alignItems: "center",
    justifyContent: "center",
  },
  checkedCircle: {
    width: scales(32),
    height: scales(32),
    borderRadius: scales(16),
    backgroundColor: colors.lightGreen,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: scales(6),
  },
  checkedIcon: {
    width: scales(16),
    height: scales(16),
    tintColor: colors.white,
    resizeMode: "contain",
  },
  changeText: {
    fontFamily: fontFamily.bold,
    fontSize: scales(11),
    color: colors.white,
  },
  videoDropRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.transparentWhite5,
    borderRadius: scales(16),
    padding: scales(14),
    borderWidth: 1,
    borderColor: colors.transparentWhite15,
    marginTop: scales(8),
  },
  videoDropLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: scales(12),
    flex: 1,
    marginRight: scales(8),
  },
  videoIconRing: {
    width: scales(44),
    height: scales(44),
    borderRadius: scales(22),
    backgroundColor: "rgba(245, 60, 109, 0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  videoIconRingSelected: { backgroundColor: "rgba(0, 200, 150, 0.15)" },
  videoDropIcon: {
    width: scales(22),
    height: scales(22),
    tintColor: colors.storyRing,
    resizeMode: "contain",
  },
  videoDropTextWrapper: { flex: 1 },
  videoDropTitle: {
    fontFamily: fontFamily.semiBold,
    fontSize: scales(14),
    color: colors.white,
  },
  videoDropSubtitle: {
    fontFamily: fontFamily.regular,
    fontSize: scales(12),
    color: "rgba(255, 255, 255, 0.5)",
    marginTop: scales(2),
  },
  videoStatusPill: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: scales(16),
    paddingHorizontal: scales(12),
    paddingVertical: scales(6),
    flexDirection: "row",
    alignItems: "center",
    gap: scales(6),
  },
  videoStatusPillSelected: {
    backgroundColor: "rgba(0, 200, 150, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(0, 200, 150, 0.3)",
  },
  miniCheckIcon: {
    width: scales(12),
    height: scales(12),
    tintColor: colors.lightGreen,
    resizeMode: "contain",
  },
  videoStatusText: {
    fontFamily: fontFamily.medium,
    fontSize: scales(12),
    color: colors.white,
  },
  videoStatusTextSelected: {
    color: colors.lightGreen,
    fontFamily: fontFamily.bold,
  },
  switchRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.transparentWhite5,
    borderRadius: scales(16),
    paddingHorizontal: scales(16),
    paddingVertical: scales(14),
    borderWidth: 1,
    borderColor: colors.transparentWhite12,
    marginTop: scales(10),
  },
  switchRowLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    marginRight: scales(12),
    gap: scales(12),
  },
  switchIconCircle: {
    width: scales(38),
    height: scales(38),
    borderRadius: scales(19),
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  switchIcon: {
    width: scales(18),
    height: scales(18),
    tintColor: colors.storyRing,
    resizeMode: "contain",
  },
  switchTextContainer: { flex: 1 },
  switchTitle: {
    fontFamily: fontFamily.semiBold,
    fontSize: scales(14),
    color: colors.white,
  },
  switchSubtitle: {
    fontFamily: fontFamily.regular,
    fontSize: scales(12),
    color: "rgba(255, 255, 255, 0.5)",
    marginTop: scales(2),
  },
  conditionalInputContainer: { marginTop: scales(8) },
  locationInputWrapper: { marginTop: scales(4) },
  specsRow: {
    flexDirection: "row",
    gap: scales(10),
    marginTop: scales(4),
  },
  specInputBox: {
    flex: 1,
  },
  castSelectedStrip: {
    paddingVertical: scales(8),
  },
  castMemberCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.transparentWhite5,
    borderWidth: 1,
    borderColor: colors.transparentWhite15,
    borderRadius: scales(25),
    paddingVertical: scales(6),
    paddingHorizontal: scales(12),
    marginRight: scales(8),
    gap: scales(8),
  },
  castAvatar: {
    width: scales(30),
    height: scales(30),
    borderRadius: scales(15),
  },
  castNameText: {
    color: colors.white,
    fontFamily: fontFamily.semiBold,
    fontSize: scales(13),
  },
  castRoleBadge: {
    backgroundColor: "rgba(245, 60, 109, 0.2)",
    borderRadius: scales(10),
    paddingHorizontal: scales(8),
    paddingVertical: scales(2),
  },
  castRoleText: {
    color: colors.storyRing,
    fontFamily: fontFamily.bold,
    fontSize: scales(11),
  },
  removeCastBtn: {
    paddingLeft: scales(4),
    paddingRight: scales(2),
  },
  removeCastText: {
    color: "rgba(255, 255, 255, 0.5)",
    fontFamily: fontFamily.bold,
    fontSize: scales(14),
  },
  addCastButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.transparentWhite5,
    borderWidth: 1,
    borderColor: colors.storyRing,
    borderRadius: scales(14),
    paddingVertical: scales(12),
    marginTop: scales(8),
    gap: scales(8),
  },
  addCastButtonText: {
    color: colors.storyRing,
    fontFamily: fontFamily.bold,
    fontSize: scales(14),
  },
  searchContainer: {
    backgroundColor: colors.transparentWhite5,
    borderRadius: scales(16),
    borderWidth: 1,
    borderColor: colors.transparentWhite15,
    padding: scales(14),
    marginTop: scales(10),
  },
  searchHeaderTitle: {
    color: colors.white,
    fontFamily: fontFamily.bold,
    fontSize: scales(14),
    marginBottom: scales(4),
  },
  roleFilterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: scales(6),
    marginTop: scales(10),
    marginBottom: scales(10),
  },
  roleChip: {
    paddingHorizontal: scales(10),
    paddingVertical: scales(6),
    borderRadius: scales(14),
    backgroundColor: colors.transparentWhite10,
    borderWidth: 1,
    borderColor: colors.transparentWhite15,
  },
  roleChipActive: {
    backgroundColor: colors.storyRing,
    borderColor: colors.storyRing,
  },
  roleChipText: {
    color: "rgba(255, 255, 255, 0.7)",
    fontFamily: fontFamily.medium,
    fontSize: scales(11),
  },
  roleChipTextActive: {
    color: colors.white,
    fontFamily: fontFamily.bold,
  },
  searchResultsList: {
    maxHeight: scales(240),
    marginTop: scales(6),
  },
  userResultRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: scales(10),
    borderBottomWidth: 1,
    borderBottomColor: colors.transparentWhite10,
  },
  userResultLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: scales(10),
  },
  userResultAvatar: {
    width: scales(38),
    height: scales(38),
    borderRadius: scales(19),
  },
  userResultName: {
    color: colors.white,
    fontFamily: fontFamily.semiBold,
    fontSize: scales(14),
  },
  userResultHandle: {
    color: "rgba(255, 255, 255, 0.4)",
    fontFamily: fontFamily.regular,
    fontSize: scales(12),
  },
  addUserActionPill: {
    backgroundColor: "rgba(245, 60, 109, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(245, 60, 109, 0.4)",
    borderRadius: scales(14),
    paddingHorizontal: scales(12),
    paddingVertical: scales(6),
  },
  addUserActionText: {
    color: colors.storyRing,
    fontFamily: fontFamily.bold,
    fontSize: scales(12),
  },
  closeSearchBtn: {
    alignSelf: "center",
    marginTop: scales(12),
    paddingVertical: scales(6),
    paddingHorizontal: scales(16),
  },
  closeSearchText: {
    color: "rgba(255, 255, 255, 0.6)",
    fontFamily: fontFamily.medium,
    fontSize: scales(13),
  },
  tagPeopleStrip: {
    paddingVertical: scales(8),
  },
  tagPersonChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(245, 60, 109, 0.15)",
    borderWidth: 1,
    borderColor: colors.storyRing,
    borderRadius: scales(20),
    paddingVertical: scales(6),
    paddingHorizontal: scales(12),
    marginRight: scales(8),
    gap: scales(6),
  },
  tagPersonAvatar: {
    width: scales(24),
    height: scales(24),
    borderRadius: scales(12),
  },
  tagPersonHandle: {
    color: colors.white,
    fontFamily: fontFamily.semiBold,
    fontSize: scales(13),
  },
  tagButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.transparentWhite5,
    borderWidth: 1,
    borderColor: colors.storyRing,
    borderRadius: scales(14),
    paddingVertical: scales(12),
    marginTop: scales(6),
    gap: scales(8),
  },
  tagButtonText: {
    color: colors.storyRing,
    fontFamily: fontFamily.bold,
    fontSize: scales(14),
  },
  ownershipRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: colors.transparentWhite5,
    borderRadius: scales(14),
    padding: scales(14),
    borderWidth: 1,
    borderColor: colors.transparentWhite12,
    marginTop: scales(10),
    gap: scales(12),
    marginHorizontal: scales(20),
  },
  checkBox: {
    width: scales(22),
    height: scales(22),
    borderRadius: scales(6),
    borderWidth: 2,
    borderColor: colors.storyRing,
    alignItems: "center",
    justifyContent: "center",
    marginTop: scales(7),
  },
  checkBoxChecked: {
    backgroundColor: colors.storyRing,
  },
  checkBoxIcon: {
    width: scales(12),
    height: scales(12),
    tintColor: colors.white,
    resizeMode: "contain",
  },
  ownershipText: {
    color: colors.transparentWhite85,
    fontFamily: fontFamily.regular,
    fontSize: scales(12),
    lineHeight: scales(18),
    flex: 1,
  },
  disabledButton: {
    opacity: 0.5,
  },
});
