import { StyleSheet, Dimensions } from "react-native";
import { colors, scales } from "../../utils";
import { fontFamily } from "../../assets";

const { width } = Dimensions.get("window");
export const THUMB_SIZE = (width - scales(52)) / 3;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  info: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: scales(20),
    paddingVertical: scales(10),
  },
  infoLabel: {
    color: colors.white,
    fontFamily: fontFamily.bold,
    fontSize: scales(15),
  },
  infoCount: {
    color: colors.transparentWhite40,
    fontFamily: fontFamily.regular,
    fontSize: scales(13),
  },
  uploadSection: {
    paddingHorizontal: scales(20),
    marginBottom: scales(16),
  },
  uploadCard: {
    borderWidth: 1.5,
    borderColor: colors.transparentWhite15,
    borderStyle: "dashed",
    borderRadius: scales(16),
    backgroundColor: colors.transparentWhite5,
    paddingVertical: scales(24),
    paddingHorizontal: scales(16),
    alignItems: "center",
    justifyContent: "center",
  },
  uploadIconCircle: {
    width: scales(52),
    height: scales(52),
    borderRadius: scales(26),
    backgroundColor: colors.transparentWhite10,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: scales(12),
  },
  uploadIcon: {
    width: scales(26),
    height: scales(26),
    tintColor: colors.white,
    resizeMode: "contain",
  },
  uploadTitle: {
    color: colors.white,
    fontFamily: fontFamily.semiBold,
    fontSize: scales(16),
    marginBottom: scales(4),
  },
  uploadSubtitle: {
    color: colors.transparentWhite40,
    fontFamily: fontFamily.regular,
    fontSize: scales(12),
    textAlign: "center",
  },
  quickActionRow: {
    flexDirection: "row",
    gap: scales(10),
    marginTop: scales(14),
  },
  quickBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: scales(6),
    paddingVertical: scales(8),
    paddingHorizontal: scales(14),
    borderRadius: scales(20),
    backgroundColor: colors.transparentWhite10,
  },
  quickBtnIcon: {
    width: scales(14),
    height: scales(14),
    tintColor: colors.white,
    resizeMode: "contain",
  },
  quickBtnText: {
    color: colors.white,
    fontFamily: fontFamily.medium,
    fontSize: scales(12),
  },
  grid: {
    paddingHorizontal: scales(16),
    paddingBottom: scales(20),
    gap: scales(10),
  },
  gridRow: {
    gap: scales(10),
  },
  thumb: {
    width: THUMB_SIZE,
    height: THUMB_SIZE,
    borderRadius: scales(12),
    overflow: "hidden",
    backgroundColor: colors.transparentWhite5,
    position: "relative",
  },
  thumbImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  removeBtn: {
    position: "absolute",
    top: scales(6),
    right: scales(6),
    width: scales(22),
    height: scales(22),
    borderRadius: scales(11),
    backgroundColor: "rgba(0, 0, 0, 0.65)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  removeIcon: {
    width: scales(10),
    height: scales(10),
    tintColor: colors.white,
  },
  indexBadge: {
    position: "absolute",
    top: scales(6),
    left: scales(6),
    width: scales(20),
    height: scales(20),
    borderRadius: scales(10),
    backgroundColor: colors.storyRing,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 5,
  },
  indexText: {
    color: colors.white,
    fontFamily: fontFamily.bold,
    fontSize: scales(10),
  },
  videoBadge: {
    position: "absolute",
    bottom: scales(6),
    left: scales(6),
    flexDirection: "row",
    alignItems: "center",
    gap: scales(4),
    backgroundColor: "rgba(0, 0, 0, 0.65)",
    borderRadius: scales(4),
    paddingHorizontal: scales(5),
    paddingVertical: scales(2),
  },
  playIcon: {
    width: scales(8),
    height: scales(8),
    resizeMode: "contain",
  },
  durationText: {
    color: colors.white,
    fontFamily: fontFamily.bold,
    fontSize: scales(9),
  },
  addMoreTile: {
    width: THUMB_SIZE,
    height: THUMB_SIZE,
    borderRadius: scales(12),
    borderWidth: 1.5,
    borderColor: colors.transparentWhite15,
    borderStyle: "dashed",
    backgroundColor: colors.transparentWhite5,
    justifyContent: "center",
    alignItems: "center",
  },
  addMoreIconCircle: {
    width: scales(32),
    height: scales(32),
    borderRadius: scales(16),
    backgroundColor: colors.transparentWhite10,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: scales(4),
  },
  addMoreIcon: {
    width: scales(16),
    height: scales(16),
    tintColor: colors.white,
    resizeMode: "contain",
  },
  addMoreText: {
    color: colors.transparentWhite40,
    fontFamily: fontFamily.medium,
    fontSize: scales(11),
  },
  emptyStateContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: scales(30),
    paddingHorizontal: scales(20),
  },
  emptyStateText: {
    color: colors.transparentWhite40,
    fontFamily: fontFamily.regular,
    fontSize: scales(13),
    textAlign: "center",
    marginTop: scales(10),
  },
  footer: {
    paddingHorizontal: scales(20),
    paddingBottom: scales(30),
    paddingTop: scales(10),
  },
});
