export const routesConstants = {
  Login: "Login",
  Splash: "Splash",
  ForgotPassword: "ForgotPassword",
  Notification: "Notification",
  Settings: "Settings",
  BottomTabs: "BottomTabs",
  EditProfile: "EditProfile",
  SignUp: "SignUp",
  ResetPassword: "ResetPassword",
  OTP: "OTP",
  Home: "Home",
  Browse: "Browse",
  Profile: "Profile",
  editProfile: "EditProfile",
};
