export const routesConstants = {
  Login: "Login",
  Splash: "Splash",
  ForgotPassword: "ForgotPassword",
  Notification: "Notification",
  Settings: "Settings",
  BottomTabs: "BottomTabs",
  EditProfile: "EditProfile",
  SignUp: "SignUp",
  ResetPassword: "ResetPassword",
  OTP: "OTP",
  Home: "Home",
  Browse: "Browse",
  Profile: "Profile",
  editProfile: "EditProfile",
  savedPosts: "SavedPosts",
  archive: "Archive",
  followers: "Followers",
  blocked: "Blocked",
  yourActivity: "YourActivity",
  accountPrivacy: "AccountPrivacy",
  Chat: "Chat",
  aiCall: "AiCall",
  chatCard: "ChatCard",
  newChat: "NewChat",
  post: "Post",
  reels: "Reels",
};
