import { StyleSheet, Platform } from "react-native";
import { colors, scales } from "../../utils";
import { fontFamily } from "../../assets";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.background,
  },
  bufferOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
  },
  bufferRing: {
    width: scales(36),
    height: scales(36),
    borderRadius: scales(18),
    borderWidth: scales(3),
    borderColor: colors.transparentWhite40,
    borderTopColor: colors.white,
  },
  topDeck: {
    position: "absolute",
    top: Platform.OS === "ios" ? scales(16) : scales(12),
    left: scales(16),
    right: scales(16),
    zIndex: 10,
  },
  topInner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: scales(16),
    paddingVertical: scales(10),
  },
  backBtn: {
    width: scales(36),
    height: scales(36),
    borderRadius: scales(18),
    alignItems: "center",
    justifyContent: "center",
  },
  headerIcon: {
    width: scales(18),
    height: scales(18),
    resizeMode: "contain",
  },
  headerCenter: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: scales(8),
  },
  headerTitle: {
    color: colors.white,
    fontSize: scales(15),
    fontFamily: fontFamily.semiBold || fontFamily.medium,
    letterSpacing: 0.2,
  },
  headerSub: {
    color: colors.profileHandleText,
    fontSize: scales(12),
    fontFamily: fontFamily.regular,
    marginTop: scales(2),
    letterSpacing: 0.1,
  },
  settingsBtn: {
    width: scales(36),
    height: scales(36),
    borderRadius: scales(18),
    alignItems: "center",
    justifyContent: "center",
  },
  centerControlsContainer: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 5,
  },
  centerSkipBtn: {
    width: scales(48),
    height: scales(48),
    borderRadius: scales(24),
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: scales(20),
  },
  centerSkipIcon: {
    width: scales(26),
    height: scales(26),
    resizeMode: "contain",
  },
  centerPlayBtn: {
    width: scales(60),
    height: scales(60),
    borderRadius: scales(30),
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: scales(12),
    shadowColor: colors.storyRing,
    shadowOpacity: 0.5,
    shadowRadius: scales(14),
    elevation: 8,
  },
  centerPlayIcon: {
    width: scales(24),
    height: scales(24),
    resizeMode: "contain",
  },
  bottomDeck: {
    position: "absolute",
    bottom: -10,
    left: scales(16),
    right: scales(16),
    zIndex: 10,
  },
  blurPill: {
    borderRadius: scales(24),
    overflow: "hidden",
    borderWidth: 1,
    borderColor: colors.transparentWhite12,
  },
  bottomRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: scales(16),
    paddingVertical: scales(25),
  },
  scrubberWrapper: {
    flex: 1,
    marginHorizontal: scales(12),
  },
  scrubberHitArea: {
    height: scales(28),
    justifyContent: "center",
  },
  trackBg: {
    position: "absolute",
    left: 0,
    right: 0,
    height: scales(3),
    borderRadius: scales(2),
    backgroundColor: colors.transparentWhite40,
  },
  trackFill: {
    position: "absolute",
    left: 0,
    height: scales(3),
    borderRadius: scales(2),
    overflow: "hidden",
  },
  thumbDot: {
    position: "absolute",
    width: scales(13),
    height: scales(13),
    borderRadius: scales(6.5),
    marginLeft: -scales(6.5),
    top: "50%",
    marginTop: -scales(6.5),
    overflow: "hidden",
    borderWidth: 2,
    borderColor: colors.white,
    shadowColor: colors.storyRing,
    shadowOpacity: 0.8,
    shadowRadius: scales(6),
    elevation: 5,
  },
  thumbDotGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  timecode: {
    color: colors.white,
    fontSize: scales(12),
    fontFamily: fontFamily.medium || fontFamily.regular,
    fontVariant: ["tabular-nums"],
    letterSpacing: 0.8,
    opacity: 0.9,
  },
  sheetTopHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: scales(14),
    width: "100%",
  },
  sheetHeaderTitle: {
    fontSize: scales(16),
    fontFamily: fontFamily.bold,
    color: colors.white,
    flex: 1,
  },
  topDoneGradientBtn: {
    minWidth: scales(70),
    height: scales(32),
    paddingHorizontal: scales(14),
    borderRadius: scales(16),
    alignItems: "center",
    justifyContent: "center",
  },
  topDoneText: {
    color: colors.white,
    fontSize: scales(13),
    fontFamily: fontFamily.bold,
    textAlign: "center",
  },
  settingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: scales(12),
    paddingHorizontal: scales(14),
    borderRadius: scales(12),
    backgroundColor: colors.transparentWhite10,
    marginBottom: scales(8),
  },
  settingRowLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  settingLabel: {
    fontSize: scales(14),
    fontFamily: fontFamily.medium,
    color: colors.white,
  },
  settingRightValue: {
    fontSize: scales(13),
    fontFamily: fontFamily.regular,
    color: colors.transparentWhite85,
  },
  backHeaderBtn: {
    flexDirection: "row",
    alignItems: "center",
  },
  backText: {
    color: colors.white,
    fontSize: scales(14),
    fontFamily: fontFamily.semiBold,
    marginLeft: scales(6),
  },
  qualityOption: {
    position: "relative",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: scales(12),
    paddingHorizontal: scales(14),
    borderRadius: scales(12),
    marginVertical: scales(2),
    overflow: "hidden",
    backgroundColor: colors.transparentWhite10,
  },
  qualityOptionLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: scales(10),
    zIndex: 2,
  },
  qualityText: {
    color: colors.transparentWhite85,
    fontSize: scales(14),
    fontFamily: fontFamily.semiBold || fontFamily.medium,
  },
  qualityTextSelected: {
    color: colors.white,
    fontFamily: fontFamily.bold,
  },
  qualityDesc: {
    color: colors.transparentWhite40,
    fontSize: scales(11),
    fontFamily: fontFamily.regular,
    marginTop: scales(2),
  },
  checkBadge: {
    width: scales(22),
    height: scales(22),
    borderRadius: scales(11),
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  checkIcon: {
    width: scales(14),
    height: scales(14),
    resizeMode: "contain",
  },
  actionIcon: {
    width: scales(20),
    height: scales(20),
    resizeMode: "contain",
  },
});
